key: MT::Plugin::@Style_MT42_Template_2nd
name: @Style_MT42_Template_2nd
description: @Style Template for MTOS/MT4.2
author_name: @Style
author_link: http://atstyle.biz/
doc_link: http://atstyle.biz/theme_temp/free/42_2cn2/
version: V1.0



template_sets:
  at_style_mt42_2nd_template_set:
    label: @Style_MT4.2_Template_2nd
    base_path: templates
    order: 100

    templates:
      index:
        feed_recent:
          label: Feed - Recent Entries
          outfile: atom.xml
          rebuild_me: 1
        javascript:
          label: JavaScript
          outfile: mt.js
          rebuild_me: 1
        main_index:
          label: Main Index
          outfile: index.html
          rebuild_me: 1
        rsd:
          label: RSD
          outfile: rsd.xml
          rebuild_me: 1
        styles:
          label: Stylesheet
          outfile: styles.css
          rebuild_me: 1
        archive_index:
          label: Archive Index
          outfile: archives.html
          rebuild_me: 1

      page:
        page:
          label: Page
          mappings:
            page_archive:
              archive_type: Page
              file_template: %-c/%-f

      archive:
        category_entry_listing:
          label: Category Entry Listing
          mappings:
            category:
              archive_type: Category
              file_template: %-c/%i

        monthly_entry_listing:
          label: Monthly Entry Listing
          mappings:
            monthly:
              archive_type: Monthly
              file_template: %y/%m/%i

      individual:
        entry:
          label: Entry
          mappings:
            entry_archive:
              archive_type: Individual
              file_template: %y/%m/%-f


      module:
        html_head:
          label: HTML Head
        comments:
          label: Comments
        sidebar:
          label: Sidebar
        trackbacks:
          label: TrackBacks
        banner_footer:
          label: Banner Footer
        banner_header:
          label: Banner Header
        entry_summary:
          label: Entry Summary

      system:
        comment_preview:
          label: Comment Preview
        comment_response:
          label: Comment Response
        dynamic_error:
          label: Dynamic Error
        popup_image:
          label: Popup Image
        search_results:
          label: Search Results

      widget:
        widget_templates/sidebar_category:
          label: カテゴリ
        widget_templates/sidebar_entry:
          label: 最近のブログ記事
        widget_templates/sidebar_page:
          label: ウェブページ
        widget_templates/sidebar_archive:
          label: アーカイブ
        widget_templates/sidebar_tag:
          label: タグクラウド
        widget_templates/sidebar_comment:
          label: コメント
        widget_templates/sidebar_trackback:
          label: トラックバック
        widget_templates/sidebar_photo:
          label: フォト
        widget_templates/sidebar_feed:
          label: フィード
        widget_templates/sidebar_powered:
          label: パワード
        widget_templates/sidebar_search:
          label: 検索
        widget_templates/sidebar_creative_commons:
          label: クリエイティブコモンズ


      widgetset:
        sidebar:
          order: 1000
          label: サイドバー
          widgets:
            - カテゴリ
            - 最近のブログ記事
            - ウェブページ
            - アーカイブ
            - タグクラウド
            - コメント
            - トラックバック
            - フォト
            - フィード
            - パワード
            - 検索
            - クリエイティブコモンズ
